# Generated by Django 6.0.4 on 2026-05-25 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('constructions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('signing_date', models.DateField(verbose_name='Data de assinatura')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('validity_days', models.IntegerField(verbose_name='Dias de validade')),
                ('document', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Documento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company', verbose_name='Empresa')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructions.construction', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['id'],
            },
        ),
    ]
