# Generated by Django 6.0.4 on 2026-05-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_options_alter_company_corporate_name'),
        ('employees', '0003_alter_employee_options_alter_employee_address_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('type', models.CharField(choices=[('road', 'Rodovia'), ('bridge', 'Ponte'), ('building', 'Edifício'), ('sanitation', 'Saneamento'), ('urban', 'Urbanização'), ('other', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('in_progress', 'Em Andamento'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='planned', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('expected_end_date', models.DateField(verbose_name='Previsão de Término')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Total (R$)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Foto')),
                ('report', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Relatório')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company', verbose_name='Empresa')),
                ('employees', models.ManyToManyField(blank=True, to='employees.employee', verbose_name='Funcionários')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Construction',
                'verbose_name_plural': 'Constructions',
                'ordering': ['id'],
            },
        ),
    ]
