# Generated by Django 6.0.4 on 2026-05-25 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructions', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='Data da visita')),
                ('status_found', models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular'), ('partial', 'Parcialmente Regular'), ('critical', 'Crítico')], max_length=20, verbose_name='Status encontrado')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('is_compliant', models.BooleanField(default=False, verbose_name='Em conformidade')),
                ('score', models.FloatField(verbose_name='Pontuação')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructions.construction', verbose_name='Obra')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Fiscal')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-visit_date'],
            },
        ),
    ]
