# Generated by Django 6.0.4 on 2026-05-25 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Número')),
                ('issue_date', models.DateField(verbose_name='Data de emissão')),
                ('conclusion', models.TextField(verbose_name='Conclusão')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspection', verbose_name='Inspeção')),
            ],
            options={
                'verbose_name': 'Audit Report',
                'verbose_name_plural': 'Audit Reports',
                'ordering': ['-issue_date'],
            },
        ),
    ]
