# Generated by Django 6.0.4 on 2026-05-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('type', models.CharField(choices=[('STREET', 'Rua'), ('AVENUE', 'Avenida'), ('SQUARE', 'Praça'), ('PARK', 'Parque'), ('ALLEY', 'Viela'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('is_paved', models.BooleanField(default=False, verbose_name='Pavimentado')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['id'],
            },
        ),
    ]
