# Generated by Django 6.0.4 on 2026-05-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_options_alter_company_corporate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('type', models.CharField(choices=[('excavator', 'Escavadeira'), ('crane', 'Guindaste'), ('truck', 'Caminhão'), ('bulldozer', 'Bulldozer'), ('concrete_mixer', 'Betoneira'), ('compactor', 'Compactador'), ('other', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diária (R$)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
                'ordering': ['name'],
            },
        ),
    ]
