# Generated by Django 6.0.4 on 2026-05-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructions', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField(verbose_name='Data de Alocação')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('usage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo de Uso (R$)')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.construction', verbose_name='Obra')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Construction Equipment',
                'verbose_name_plural': 'Construction Equipments',
                'ordering': ['id'],
            },
        ),
    ]
