# Generated by Django 6.0.4 on 2026-05-25 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('national_id', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('position', models.CharField(choices=[('engineer', 'Engenheiro(a)'), ('architect', 'Arquiteto(a)'), ('foreman', 'Mestre de Obras'), ('inspector', 'Fiscal'), ('worker', 'Operário(a)'), ('manager', 'Gerente')], max_length=30, verbose_name='Cargo')),
                ('hire_date', models.DateField(verbose_name='Data de Admissão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.company', verbose_name='Empresa')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
