# Generated by Django 6.0.4 on 2026-05-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('national_id', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('address', models.CharField(max_length=200, verbose_name='Endereco')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('position', models.CharField(choices=[('engineer', 'Engenheiro(a)'), ('architect', 'Arquiteto(a)'), ('foreman', 'Mestre de Obras'), ('inspector', 'Fiscal'), ('worker', 'Operario(a)'), ('manager', 'Gerente')], max_length=30, verbose_name='Cargo')),
                ('hire_date', models.DateField(verbose_name='Data de Admissao')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
