# Generated by Django 6.0.4 on 2026-05-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('engineer', 'Engenheiro(a)'), ('architect', 'Arquiteto(a)'), ('foreman', 'Mestre de Obras'), ('inspector', 'Fiscal'), ('worker', 'Operário(a)'), ('manager', 'Gerente')], max_length=30, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário'),
        ),
    ]
