# Generated by Django 6.0.4 on 2026-05-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
        ('constructions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('type', models.CharField(choices=[('accident', 'Acidente'), ('structural', 'Problema Estrutural'), ('environmental', 'Dano Ambiental'), ('vandalism', 'Vandalismo'), ('delay', 'Atraso'), ('other', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('occurred_at', models.DateTimeField(verbose_name='Ocorrido em')),
                ('severity', models.IntegerField(verbose_name='Severidade (1-5)')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructions.construction', verbose_name='Obra')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citizens.citizen', verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
